### ISSUE TITLE
Add organisationUnit-User-Assigment to waffle

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/nrcwebapps#3]
The repo: https://github.com/EyeSeeTea/organisationUnit-User-Assigment should be added to waffle so we can add issues to it.

**Comment by adrianq** [comment]
It is in waffle https://waffle.io/EyeSeeTea/organisationUnit-User-Assigment but you are mixing up projects again ;) orgOU-user-assignment is not a nrc web app!
