### ISSUE TITLE
JS not working on custom entries

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/nrcwebapps#5]
Go to dataset "AF-Afghanistan Shelter Mandatory" (+ select any of the others) and Get Data. The entries are loaded, but:

- The filter fields does nothing.
- Button show/hide sections: if you click one of the sections, the whole page is cleared.

@adrianq We can investigate where the problem lies and fix it if possible or (at least for the moment) hide those fields.

Do we have identified some other custom entries which may have these problems?

**Comment by adrianq** [comment]
@tokland The data entry is supposed to be read-only. I think we are disabling every component in the form (correct me if I am wrong). It keeps the same look&feel as in the data entry but it is definitely not supposed to be used to register new data. Said that IMO all we can do is make components read-only in a generic way. There are always gonna be corner cases in custom forms we can not deal with.  Can we disable the search field as well? Not sure why the javascript command that makes the rest of the textfields read-only  is not affecting this one. Can we maybe do the same with the checkbox? Sounds sensible?

**Comment by tokland** [comment]
Those two controls I refererred to are just visualitzation controls, I guess it made sense not to disable those.

![custom-entries](https://cloud.githubusercontent.com/assets/24643/24105390/0274081a-0d85-11e7-9d27-eb91378d5401.png)

I'll hide these two (non-working) widgets.

**Comment by adrianq** [comment]
Yep, I had in mind what controls you were talking about. I was proposing to disable them because it would be more generic for future customs forms (disable every single textfield and checkbox in the form). Anyway, let's hide it for now...

**Comment by tokland** [comment]
Oh, I get you now. I've checked the code, only input fields are explicitly disabled: `$('.entryfield').attr('readonly', 'readonly');`. Anyway, it's good to hide those non-working controls.

**Comment by adrianq** [comment]
Good that we are on the same page now :) Closing the card for now. Maybe we can implement something nicer in the future but it is good enough for now.
